"""
School name alias tables.

Every raw source spells college names differently:
  - PFF ("team_name"):   short, all-caps codes, e.g. "E CAROLINA", "MIAMI FL"
  - Combine ("college"): mixed, sometimes abbreviated, e.g. "Ohio St.", "Ohio State"
  - CFBD ("team"):       mostly full names, e.g. "East Carolina", occasional
                         unicode (San José State) or shorthand (NC State, Ole Miss)

We normalize all three onto one canonical school string (loosely modeled on
CFBD's own naming, since it is the most complete/standard list of D-I
programs) so that a player can be matched across sources on
(normalized_name, canonical_school[, season]).

These dicts cover every school that appears in the PFF QB files (2014-2015)
and the combine QB rows (2016-2026) as of this writing. New PFF years
(2016-2025) may introduce team codes for schools that recently joined FBS
(e.g. Coastal Carolina, James Madison, Sam Houston, Jacksonville State) or
codes we simply haven't seen yet -- normalize.get_canonical_school() falls
back to a best-effort title-cased pass-through for anything not listed here
and logs it so a human can extend this file.
"""

from __future__ import annotations

# Raw PFF ``team_name`` (all caps, PFF's short school codes) -> canonical school.
PFF_SCHOOL_ALIASES: dict[str, str] = {
    "AIR FORCE": "Air Force",
    "AKRON": "Akron",
    "ALABAMA": "Alabama",
    "APP STATE": "App State",
    "ARIZONA": "Arizona",
    "ARIZONA ST": "Arizona State",
    "ARK STATE": "Arkansas State",
    "ARKANSAS": "Arkansas",
    "ARMY": "Army",
    "AUBURN": "Auburn",
    "BALL ST": "Ball State",
    "BAYLOR": "Baylor",
    "BOISE ST": "Boise State",
    "BOSTON COL": "Boston College",
    "BOWL GREEN": "Bowling Green",
    "BUFFALO": "Buffalo",
    "C MICHIGAN": "Central Michigan",
    "CAL": "California",
    "CHARLOTTE": "Charlotte",
    "CINCINNATI": "Cincinnati",
    "CLEMSON": "Clemson",
    "COLO STATE": "Colorado State",
    "COLORADO": "Colorado",
    "DOMINION": "Old Dominion",
    "DUKE": "Duke",
    "E CAROLINA": "East Carolina",
    "E MICHIGAN": "Eastern Michigan",
    "FAU": "Florida Atlantic",
    "FIU": "Florida International",
    "FLORIDA": "Florida",
    "FLORIDA ST": "Florida State",
    "FRESNO ST": "Fresno State",
    "GA SOUTHRN": "Georgia Southern",
    "GA STATE": "Georgia State",
    "GA TECH": "Georgia Tech",
    "GEORGIA": "Georgia",
    "HAWAII": "Hawaii",
    "HOUSTON": "Houston",
    "IDAHO": "Idaho",
    "ILLINOIS": "Illinois",
    "INDIANA": "Indiana",
    "IOWA": "Iowa",
    "IOWA STATE": "Iowa State",
    "KANSAS": "Kansas",
    "KANSAS ST": "Kansas State",
    "KENT STATE": "Kent State",
    "KENTUCKY": "Kentucky",
    "LA LAFAYET": "Louisiana",
    "LA MONROE": "UL Monroe",
    "LA TECH": "Louisiana Tech",
    "LOUISVILLE": "Louisville",
    "LSU": "LSU",
    "MARSHALL": "Marshall",
    "MARYLAND": "Maryland",
    "MEMPHIS": "Memphis",
    "MIAMI FL": "Miami",
    "MIAMI OH": "Miami (OH)",
    "MICH STATE": "Michigan State",
    "MICHIGAN": "Michigan",
    "MIDDLE TN": "Middle Tennessee",
    "MINNESOTA": "Minnesota",
    "MISS STATE": "Mississippi State",
    "MISSOURI": "Missouri",
    "N CAROLINA": "North Carolina",
    "N ILLINOIS": "Northern Illinois",
    "N TEXAS": "North Texas",
    "NAVY": "Navy",
    "NC STATE": "NC State",
    "NEBRASKA": "Nebraska",
    "NEVADA": "Nevada",
    "NEW MEX ST": "New Mexico State",
    "NEW MEXICO": "New Mexico",
    "NOTRE DAME": "Notre Dame",
    "NWESTERN": "Northwestern",
    "OHIO": "Ohio",
    "OHIO STATE": "Ohio State",
    "OKLA STATE": "Oklahoma State",
    "OKLAHOMA": "Oklahoma",
    "OLE MISS": "Ole Miss",
    "OREGON": "Oregon",
    "OREGON ST": "Oregon State",
    "PENN STATE": "Penn State",
    "PITTSBURGH": "Pittsburgh",
    "PURDUE": "Purdue",
    "RICE": "Rice",
    "RUTGERS": "Rutgers",
    "S ALABAMA": "South Alabama",
    "S CAROLINA": "South Carolina",
    "S DIEGO ST": "San Diego State",
    "S JOSE ST": "San Jose State",
    "SMU": "SMU",
    "SO MISS": "Southern Miss",
    "STANFORD": "Stanford",
    "SYRACUSE": "Syracuse",
    "TCU": "TCU",
    "TEMPLE": "Temple",
    "TENNESSEE": "Tennessee",
    "TEXAS": "Texas",
    "TEXAS A&M": "Texas A&M",
    "TEXAS ST": "Texas State",
    "TEXAS TECH": "Texas Tech",
    "TOLEDO": "Toledo",
    "TROY": "Troy",
    "TULANE": "Tulane",
    "TULSA": "Tulsa",
    "UAB": "UAB",
    "UCF": "UCF",
    "UCLA": "UCLA",
    "UCONN": "Connecticut",
    "UMASS": "Massachusetts",
    "UNLV": "UNLV",
    "USC": "USC",
    "USF": "South Florida",
    "UTAH": "Utah",
    "UTAH ST": "Utah State",
    "UTEP": "UTEP",
    "UTSA": "UTSA",
    "VA TECH": "Virginia Tech",
    "VANDERBILT": "Vanderbilt",
    "VIRGINIA": "Virginia",
    "W KENTUCKY": "Western Kentucky",
    "W MICHIGAN": "Western Michigan",
    "W VIRGINIA": "West Virginia",
    "WAKE": "Wake Forest",
    "WASH STATE": "Washington State",
    "WASHINGTON": "Washington",
    "WISCONSIN": "Wisconsin",
    "WYOMING": "Wyoming",
    # --- FCS / small-school codes. These only show up in the PFF families
    # with looser inclusion thresholds (time-in-pocket, passing-pressure,
    # passing-concept, passing-depth) rather than passing-grades, since
    # backups/gadget players and non-FBS QBs clear those thresholds too.
    "ABILENE CH": "Abilene Christian",
    "ALAB A&M": "Alabama A&M",
    "ALBANY": "UAlbany",
    "ALCORN ST": "Alcorn State",
    "ARKAPB": "Arkansas-Pine Bluff",
    "AUSTINPEAY": "Austin Peay",
    "BETH COOK": "Bethune-Cookman",
    "BUCKNELL": "Bucknell",
    "BYU": "BYU",
    "CAL POLY": "Cal Poly",
    "CAMPBELL": "Campbell",
    "CENT ARK": "Central Arkansas",
    "CHARLES SO": "Charleston Southern",
    "CHATTNOOGA": "Chattanooga",
    "CITADEL": "The Citadel",
    "COLGATE": "Colgate",
    "DELAWARE": "Delaware",
    "DELWARE ST": "Delaware State",
    "DUQUESNE": "Duquesne",
    "E ILLINOIS": "Eastern Illinois",
    "E KENTUCKY": "Eastern Kentucky",
    "E WASHGTON": "Eastern Washington",
    "ELON": "Elon",
    "FL A&M": "Florida A&M",
    "FORDHAM": "Fordham",
    "FURMAN": "Furman",
    "GARD-WEBB": "Gardner-Webb",
    "GRAMBLING": "Grambling",
    "HAMPTON": "Hampton",
    "HOWARD": "Howard",
    "IDAHO ST": "Idaho State",
    "ILL STATE": "Illinois State",
    "INCAR WORD": "Incarnate Word",
    "INDIANA ST": "Indiana State",
    "JACKSON ST": "Jackson State",
    "JAMES MAD": "James Madison",
    "JVILLE ST": "Jacksonville State",
    "LAMAR": "Lamar",
    "LIBERTY": "Liberty",
    "MAINE": "Maine",
    "MCNEESE": "McNeese",
    "MO STATE": "Missouri State",
    "MONMOUTH": "Monmouth",
    "MONTANA": "Montana",
    "MONTANA ST": "Montana State",
    "MORGAN ST": "Morgan State",
    "MS VLY ST": "Mississippi Valley State",
    "MURRAY ST": "Murray State",
    "N ARIZONA": "Northern Arizona",
    "N COLORADO": "Northern Colorado",
    "N DAK ST": "North Dakota State",
    "N DAKOTA": "North Dakota",
    "N IOWA": "Northern Iowa",
    "NC A&T": "North Carolina A&T",
    "NC CENT": "North Carolina Central",
    "NEW HAMP": "New Hampshire",
    "NICHOLLS": "Nicholls",
    "NORFOLK": "Norfolk State",
    "NWSTATE": "Northwestern State",
    "PORTLAND": "Portland State",
    "PRESBYTERN": "Presbyterian",
    "PRVIEW A&M": "Prairie View A&M",
    "RHODE ISLD": "Rhode Island",
    "RICHMOND": "Richmond",
    "S DAK ST": "South Dakota State",
    "S DAKOTA": "South Dakota",
    "S ILLINOIS": "Southern Illinois",
    "SACRAMENTO": "Sacramento State",
    "SAMFORD": "Samford",
    "SAN DIEGO": "San Diego",
    "SCAR STATE": "South Carolina State",
    "SE LA": "SE Louisiana",
    "SE MO ST": "Southeast Missouri State",
    "SM HOUSTON": "Sam Houston",
    "SO UTAH": "Southern Utah",
    "SOUTHERN U": "Southern",
    "STF AUSTIN": "Stephen F. Austin",
    "STNY BROOK": "Stony Brook",
    "SVANNAH ST": "Savannah St",
    "TENN MARTN": "UT Martin",
    "TENN TECH": "Tennessee Tech",
    "TOWSON": "Towson",
    "UC DAVIS": "UC Davis",
    "VA MILT IN": "VMI",
    "VILLANOVA": "Villanova",
    "W CAROLINA": "Western Carolina",
    "W ILLINOIS": "Western Illinois",
    "WAGNER": "Wagner",
    "WEBER ST": "Weber State",
    "WM & MARY": "William & Mary",
    "WOFFORD": "Wofford",
    "YALE": "Yale",
    "YNGTOWN ST": "Youngstown State",
}

# Raw combine ``college`` -> canonical school. Combine data is internally
# inconsistent across draft years (e.g. both "Ohio St." and "Ohio State",
# both "Miami" and "Miami (FL)" appear), so both spellings are mapped here.
COMBINE_SCHOOL_ALIASES: dict[str, str] = {
    "Alabama": "Alabama",
    "Appalachian St.": "App State",
    "Arkansas": "Arkansas",
    "Auburn": "Auburn",
    "BYU": "BYU",
    "Baylor": "Baylor",
    "Boise State": "Boise State",
    "Brown": "Brown",
    "Buffalo": "Buffalo",
    "California": "California",
    "Central Michigan": "Central Michigan",
    "Cincinnati": "Cincinnati",
    "Clemson": "Clemson",
    "Colorado": "Colorado",
    "Connecticut": "Connecticut",
    "Duke": "Duke",
    "Florida": "Florida",
    "Florida International": "Florida International",
    "Florida St.": "Florida State",
    "Fresno St.": "Fresno State",
    "Georgia": "Georgia",
    "Georgia Tech": "Georgia Tech",
    "Hawaii": "Hawaii",
    "Houston": "Houston",
    "Illinois": "Illinois",
    "Indiana": "Indiana",
    "Iowa": "Iowa",
    "Iowa St.": "Iowa State",
    "Kansas": "Kansas",
    "Kansas St.": "Kansas State",
    "Kent St.": "Kent State",
    "Kentucky": "Kentucky",
    "LSU": "LSU",
    "Liberty": "Liberty",
    "Louisiana Tech": "Louisiana Tech",
    "Louisville": "Louisville",
    "Marshall": "Marshall",
    "Memphis": "Memphis",
    "Miami": "Miami",
    "Miami (FL)": "Miami",
    "Michigan": "Michigan",
    "Michigan State": "Michigan State",
    "Minnesota": "Minnesota",
    "Mississippi": "Ole Miss",
    "Mississippi State": "Mississippi State",
    "Missouri": "Missouri",
    "Nebraska": "Nebraska",
    "Nevada": "Nevada",
    "North Carolina": "North Carolina",
    "North Carolina State": "NC State",
    "North Dakota St.": "North Dakota State",
    "North Dakota State": "North Dakota State",
    "Northwestern": "Northwestern",
    "Notre Dame": "Notre Dame",
    "Ohio St.": "Ohio State",
    "Ohio State": "Ohio State",
    "Oklahoma": "Oklahoma",
    "Oklahoma State": "Oklahoma State",
    "Oregon": "Oregon",
    "Oregon State": "Oregon State",
    "Penn St.": "Penn State",
    "Penn State": "Penn State",
    "Pittsburgh": "Pittsburgh",
    "Princeton": "Princeton",
    "Purdue": "Purdue",
    "Richmond": "Richmond",
    "Shepherd": "Shepherd",
    "South Carolina": "South Carolina",
    "South Florida": "South Florida",
    "Southeastern Louisiana": "SE Louisiana",
    "Stanford": "Stanford",
    "Syracuse": "Syracuse",
    "TCU": "TCU",
    "Tennessee": "Tennessee",
    "Texas": "Texas",
    "Texas A&M": "Texas A&M",
    "Texas Tech": "Texas Tech",
    "Toledo": "Toledo",
    "Tulane": "Tulane",
    "Tulsa": "Tulsa",
    "UCLA": "UCLA",
    "USC": "USC",
    "Utah State": "Utah State",
    "Vanderbilt": "Vanderbilt",
    "Virginia": "Virginia",
    "Virginia Tech": "Virginia Tech",
    "Washington": "Washington",
    "Washington State": "Washington State",
    "West Virginia": "West Virginia",
    "Western Kentucky": "Western Kentucky",
    "Western Michigan": "Western Michigan",
    "Wisconsin": "Wisconsin",
    "Wyoming": "Wyoming",
}

# Raw CFBD ``team`` -> canonical school. CFBD is already close to canonical;
# this only needs to cover the handful of spellings that differ from the
# canonical forms chosen above (accented characters, apostrophes, etc).
CFBD_SCHOOL_ALIASES: dict[str, str] = {
    "Hawai'i": "Hawaii",
    "San José State": "San Jose State",
    "Miami (OH)": "Miami (OH)",
}
